// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.Models;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(PaulDbBorkAsContext))]
    partial class PaulDbBorkAsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfApp1.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("ManufacturerID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RentalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RentalUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__3447459991503C60");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeId");

                    b.HasIndex(new[] { "Article" }, "IX_Equipment_Article");

                    b.HasIndex(new[] { "Article" }, "UQ__Equipmen__4943444AA5A50452")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("WpfApp1.Models.EquipmentType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId")
                        .HasName("PK__Equipmen__516F03958E4C0D0E");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("WpfApp1.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManufacturerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ManufacturerId")
                        .HasName("PK__Manufact__357E5CA13BA1B9DF");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("WpfApp1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientUserId")
                        .HasColumnType("int")
                        .HasColumnName("ClientUserID");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<decimal>("OrderNumber")
                        .HasColumnType("decimal(10, 1)");

                    b.Property<int>("PickupPointId")
                        .HasColumnType("int")
                        .HasColumnName("PickupPointID");

                    b.Property<decimal>("ReceiptCode")
                        .HasColumnType("decimal(10, 1)");

                    b.Property<int>("RentalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF16032349");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "OrderNumber" }, "IX_Orders_OrderNumber");

                    b.HasIndex(new[] { "RentalStartDate" }, "IX_Orders_RentalStartDate");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WpfApp1.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__OrderSta__C8EE2043DF95AD67");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("WpfApp1.Models.PickupPoint", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PointID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PointId")
                        .HasName("PK__PickupPo__40A97781796682A2");

                    b.ToTable("PickupPoints");
                });

            modelBuilder.Entity("WpfApp1.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A9B72DA1C");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WpfApp1.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666947487E062");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("WpfApp1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACD992035B");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Login" }, "IX_Users_Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WpfApp1.Models.Equipment", b =>
                {
                    b.HasOne("WpfApp1.Models.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipment_Manufacturers");

                    b.HasOne("WpfApp1.Models.Supplier", "Supplier")
                        .WithMany("Equipment")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipment_Suppliers");

                    b.HasOne("WpfApp1.Models.EquipmentType", "Type")
                        .WithMany("Equipment")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipment_Types");

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WpfApp1.Models.Order", b =>
                {
                    b.HasOne("WpfApp1.Models.User", "ClientUser")
                        .WithMany("Orders")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_ClientUsers");

                    b.HasOne("WpfApp1.Models.Equipment", "Equipment")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Equipment");

                    b.HasOne("WpfApp1.Models.PickupPoint", "PickupPoint")
                        .WithMany("Orders")
                        .HasForeignKey("PickupPointId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_PickupPoints");

                    b.HasOne("WpfApp1.Models.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Statuses");

                    b.Navigation("ClientUser");

                    b.Navigation("Equipment");

                    b.Navigation("PickupPoint");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WpfApp1.Models.User", b =>
                {
                    b.HasOne("WpfApp1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WpfApp1.Models.Equipment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WpfApp1.Models.EquipmentType", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("WpfApp1.Models.Manufacturer", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("WpfApp1.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WpfApp1.Models.PickupPoint", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WpfApp1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WpfApp1.Models.Supplier", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("WpfApp1.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
